### ISSUE TITLE
Watch task - autoinstall cargo-watch

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed-quickstart#7]
> Nice addition. Ideally, it would automatically install cargo-watch, but I've been unable to get it to do so; must install explicitly before.

I tried to uninstall `cargo-watch` and then run `cargo make watch` - it fails with a `cargo-watch` compilation error, because `cargo-make` installs version `7.0.8` (see [source code](https://github.com/sagiegurari/cargo-make/blob/296dc39e3db634b8f1eb348bdccd464f3d9e31c1/src/lib/runner.rs#L259)) which seems to be buggy. The latest version `7.2.1` works for me.

```
[tasks.watch]
description = "Build, and create wasms, then watch files for changes"
workspace = false
dependencies = ["build", "create_wasm"]
watch = { ignore_pattern="pkg/*", version="7.2.1" }
```

If it's working for you as well, please, create issue in [cargo-make repo](https://github.com/sagiegurari/cargo-make).

**Comment by David-OConnor** [comment]
Great catch! The specific error I ran into was:
```
error[E0308]: mismatched types
   --> C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9e
    |
175 |         paths: get_watches(debug, &matches),
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct
    |
    = note: expected type `std::vec::Vec<std::path::PathBuf>`
               found type `std::vec::Vec<std::string::String>`
```
Works with your change. Committed, and Submitted a PIR to `cargo-make`.

**Comment by MartinKavik** [comment]
Yeah, same error. 
I tried uninstall `cargo-watch` and run `cargo make watch` - seems to work with the latest `cargo-make`.
